### PR TITLE
Fix android targetting

### PR DESCRIPTION
**Pull request by Jake-Shadle**
* Add appropriate CMake defines so can compile the native code
* `c_char` is apparently `i8` on ARM (not sure if that applies to any and all variants)

### CODE REVIEW

**Comment by Jake-Shadle** [comment]
Note, I've only confirmed this works when targetting `aarch64-linux-android` using NDK r21d with SDK 29.

**Comment by Jake-Shadle** [comment]
It looks like `SENTRY_DSN` comes from a secret for CI and is no longer present/set.

**Comment by daxpedda** [comment]
> It looks like `SENTRY_DSN` comes from a secret for CI and is no longer present/set.

Yeah I think I can make this one public.

I will have to look into this PR on monday, thank you for your work!

**Comment by daxpedda** [comment]
Sorry for the delay!
I will actually not be able to make `SENTRY_DSN` public, so for now I will have to disable some of the CI for PRs.
In any case, in the future CI will move to using Relay and we won't need this part anymore.

**Comment by Jake-Shadle** [comment]
Cool, no worries.

**Pull request merged**
